server:
  port: 80
  servlet:
    context-path: /Bestshop
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/bestshopdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 364696762636-l8e7ndft7a56uh6sne28pj4gt0la6e2s.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1073225023867367
            client-secret: e4a4cb00ada59568cd9221ebc47e3549
            scope:
              - email
              - public_profile